- decimal_octal_conv.py
Hello, this is my pull request. Hope you have a great day :D
> decimal to octal converter

- Program/Binary_search.py
- Program/binary to hex.py
Tried my ass off to work on this piece of program
> Binary search python

- Projects/banking.py
Jiban re emti software baneili company nata mariba mate
> Our personal bank, no security just code

- Projects/image_2_sketch.py.py
- Projects/plagiarism_checker.py
I have added a python script for 2 projects one for the image to pencil sketch and the other for plagiarism checker.
> Image to pencil sketch and plagiarism checker

- Projects/python turtle graphics.py
I have created a project named: Python Turtle Graphics.
> Python project 

- Program/number_pattern.py
Interesting Number Pattern based on/without user input.
> added: number_pattern.py

- Projects/Text_to_Handwritten_Text.py
I have added a project that will convert Text to Handwritten text!
> Add a Project

- Program/random pass generator.py
a program that can generate random password according to users need of no of alphabets, numbers and symbol and can also define the length
> added a program to generate random password

- Control Mouse/Mouse_Control.py
python project for control mouse
> countrol mouse project

- Projects/Yts Discord Bot/Procfile
- Projects/Yts Discord Bot/commands.txt
- Projects/Yts Discord Bot/requirements.txt
- Projects/Yts Discord Bot/yts.py
Just get a token ID from Discord Developer and insert it in yts.py
Then you are good to go....
> Yts Discord Bot

- Projects/acronym_generator.py
**This is an acronym generator** 
The program takes input from the user and convert it into a acronym
> Initial commit

- Program/N_largest_element_in_list.py
TWO APPRAOCHES FOR FINDING GREATEST ELEMENT IN LIST
> gives the N largest element in list 2 approaches

- Program/menu_based_calc.py
It makes use of functional programming and error handling concepts to create a menu based calculator.
> Added Menu based Calculator

- Program/keylogger.py
python script to log user keystrokes.
> add keylogger.py

- Projects/bmi.py
**This is a python program to check body mass index of a person**
> Made Body Mass Index

- Program/calculator.py
Added calculator.py program in Program folder.
Please accept and add the `hacktoberfest-accepted` label.
Thank you.
> Added calculator tkinter program

- Program/Fibonacci_Numbers.py
> Find nth fibonacci number

- Program/hamming.py
I created this script when I learned for my Networking course in university, I figured it can help other people too...
Example usage:
To calculate hamming code of 10011010 (8): `python3 hamming.py -p 10011010`
To validate hamming code and display it's code bits for 011100101010 (12): `python3 hamming.py -c -p 011100101010`
> Added a tool that helps understanding hamming code

- Program/networkx-lib.py
A PR with networkx-library: helps in plotting graphs with nodes and edges ^-^
> networkx-library

- Program/QuizGame.py
Contributing to Hacktoberfest2021
> Added a Quiz Game

- Program/bubble_sort.py
I added the old and faithful bubble sort to python practice. This is actually my first python program. I usually use C++, but python is pretty cool. Definitely going to learn more
> Added bubble sort to PYTHON-PRACTICE

- Program/sorting methods.py
This file contains all the main sorting algorithms and compares the time taken by them to sort a given list.
> Added sorting methods.py

- Program/K_largestPairs
added the qs with example and also the Code
> Program for K largest pairs

- Program/string_compare.py
This function compares the binary values of two strings character by character, and prints out which string (case-insensitive) is greater.
> Added a case-insensitive string compare function

- simplegrade.py
coded a simple grading system in python in simplegrade.py
> Added a simple grading system in python
